Tool for increment numbers: TOOL_INCREMENT_NUMBERS_Private_Functions
TOOL_INCREMENT_NUMBERS_Private_Functions
Tool_increment_numbers_module » TOOL_INCREMENT_NUMBERS
Functions
void InitNumber (void)
Init module.
int GetNumber (void)
Get current number.
void IncrementNumber (void)
Increment current number.
void SetMaximumValue (int maximumValue)
Set maximum value of Number.
Detailed Description
Function Documentation
GetNumber()
int GetNumber (void)
Parameters
None
Return values
current value
References _currentNumber.
Referenced by test_increment_number(), test_init_max_val(), test_init_val(), test_reset_val_if_reach_max(), test_set_max_val(), and test_set_negative_val().
IncrementNumber()
void IncrementNumber (void)
Note
This function increases the current value by 1 until it reaches _maxValue. Otherwise it resets the value to 0.
References _currentNumber, and _maxValue.
Referenced by test_increment_number(), test_init_max_val(), test_reset_val_if_reach_max(), test_set_max_val(), and test_set_negative_val().
InitNumber()
void InitNumber (void)
Parameters
None
Return values
None
References _currentNumber, and _maxValue.
Referenced by tearDown().
SetMaximumValue()
void SetMaximumValue (int maximumValue)
Parameters
maximumValue This parameter can have a value in range from 0 to maximum value of int. If the number is less than 0 then the seting value is ignored.
Return values
None
References _maxValue.
Referenced by test_reset_val_if_reach_max(), test_set_max_val(), and test_set_negative_val().